### ISSUE TITLE
How to verify CRL

### ISSUE THREAD

**Issue by zhujintao** [hydrogen18/test-tls#3]
Server verify client certificate is revoked?

**Comment by jkahrs** [comment]
I think you can load the CRL in your server and then check it with something like https://golang.org/pkg/crypto/x509/pkix/

**Comment by hydrogen18** [comment]
I'm not really aware of how to do that off hand, or how it works in Go. This isn't the appropriate venue to ask questions, consider a site such as StackOverflow.
